# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sh' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sh
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'GoogleSignIn'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  target 'shTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sh-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sh-tvOS

  target 'sh-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
